const en = {
    "info": "Information",
    "warn": "Warning",
    "error": "Error",

    "/ad/": "Administrator",
    "/pm/": "Project manager",
    "/pd/": "Deployment staff",
    "/ps/": "Monitor staff",

    "/new/": "new",
    "/old/": "old",
    "/of/": "of",
    "/as/": "as",
    "/the/": "the",
    "/in/": "in",
    "/priority/": "priority",
    "/status/": "status",
    "/infor/": "info",
    "/title/": "title",
    "/description/": "description",
    "/approve/": "approve",
    "/approved/": "approved",
    "/unapproved/": "unapproved",

    "/but/": "but",
    "/fail/": "fail",
    "/failed/": "failed",
    "/try to/": "try to",
    "/tries to/": "tries to",
    "/tried to/": "tried to",
    
    "/with/": "with",
    "/manager/": "manager",    
    "/member/": "member",
    "/members/": "members",
    "/login/": "login",

    "/user/": "user",
    "/account/": "account",
    "/project/": "project",
    "/version/": "version",
    "/task/": "task",
    "/taskmodify/": "taskmodify",
    "/table/": "table",
    "/field/": "field",
    "/projectmember/": "projectmember",
    "/userinterface/": "",
    "/useinterfacecomponent/": "",


    "/permission/": "permission",

    "/create/": "create",
    "/add/": "add",
    "/update/": "update",
    "/modify/": "modify",
    "/remove/": "remove",
    "/delete/": "delete",
    "/purge/": "purge",
    "/destroy/": "destroy",
    "/from/": "from",
    "/to/": "to",
    "/from_1/": "from",
    "/to_1/": "to",
    "/to_2/": "to",

    "/creates/": "creates",
    "/adds/": "adds",
    "/updates/": "updates",
    "/modifies/": "modifies",
    "/removes/": "removes",
    "/deletes/": "deletes",
    "/purges/": "purges",
    "/destroys/": "destroys",

    "/created/": "created",
    "/added/": "added",
    "/updated/": "updated",
    "/modified/": "modified",
    "/removed/": "removed",
    "/deleted/": "deleted",
    "/purged/": "purged",
    "/destroyed/": "destroyed",
}

module.exports = en