const vi = {
    "info": "Thông tin",
    "warn": "Cảnh báo",
    "error": "Lỗi",

    "/new/": "mới",
    "/old/": "cũ",
    "/as/": "như là",
    "/of/": "của",
    "/the/": "",
    "/in/": "trong",
    "/priority/": "độ ưu tiên",
    "/status/": "trạng thái",
    "/infor/": "thông tin",
    "/title/": "tiêu đề",
    "/description/": "mô tả",
    "/approve/": "xác nhận",
    "/approved/": "đã xác nhận",
    "/unapproved/": "chưa xác nhận",

    "/but/": "nhưng",
    "/fail/": "thất bại",
    "/failed/": "thất bại",
    "/try to/": "cố gắng",
    "/tries to/": "cố gắng",
    "/tried to/": "đã cố gắng",

    "/ad/": "Quản trị viên",
    "/pm/": "Quản lý dự án",
    "/pd/": "Đội triển khai",
    "/ps/": "Đội giám sát",

    "/with/": "với",
    "/manager/": "người quản lý",
    "/member/": "thành viên",
    "/members/": "thành viên",

    "/login/": "đăng nhập",

    "/user/": "người dùng",
    "/account/": "tài khoản",    
    "/project/": "dự án",
    "/version/": "phiên bản",
    "/task/": "yêu cầu",
    "/taskmodify/": "thay đổi yêu cầu",
    "/table/": "bảng",
    "/field/": "trường",
    "/projectmember/": "thành viên dự án",
    "/userinterface/": "",
    "/useinterfacecomponent/": "",

    "/permission/": "phân quyền",


    "/create/": "tạo",
    "/add/": "thêm",
    "/update/": "cập nhật",
    "/modify/": "thay đổi",
    "/remove/": "loại bỏ",
    "/delete/": "xóa bỏ",
    "/purge/": "xóa sạch",
    "/destroy/": "hủy",
    "/from/": "từ",
    "/to/": "thành",
    "/from_1/": "khỏi",
    "/to_1/": "đến",
    "/to_2/": "vào",
    
    
    "/creates/": "tạo",
    "/adds/": "thêm",
    "/updates/": "cập nhật",
    "/modifies/": "thay đổi",
    "/removes/": "loại bỏ",
    "/deletes/": "xóa bỏ",
    "/purges/": "xóa sạch",
    "/destroys/": "hủy",

    "/created/": "đã tạo",
    "/added/": "đã thêm",
    "/updated/": "đã cập nhật",
    "/modified/": "đã thay đổi",
    "/removed/": "đã loại bỏ",
    "/deleted/": "đã xóa bỏ",
    "/purged/": "đã xóa sạch",
    "/destroyed/": "đã hủy",
}

module.exports = vi