const RESULT_PER_SEARCH_PAGE = 15
const DEFAULT_ERROR_CALCLATED_VALUE = "NaN"
const TOTAL_DATA_PER_PARTITION = 10000

module.exports = {
    RESULT_PER_SEARCH_PAGE,
    DEFAULT_ERROR_CALCLATED_VALUE,
    TOTAL_DATA_PER_PARTITION,
}